version: "2"

services:
  server:
    build: ./server
    container_name: backend
    ports:
      - "8080:8080"

  client:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - server
