CREATE TABLE IF NOT EXISTS events (
    id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
    groupId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    title TEXT NOT NULL,
    "datetime" INTEGER NOT NULL,
    creationDate INTEGER NOT NULL
);