CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT, 
    uuid TEXT UNIQUE NOT NULL, 
    avatarId INTEGER UNIQUE,
    email TEXT UNIQUE NOT NULL, 
    login TEXT UNIQUE NOT NULL, 
    password TEXT NOT NULL, 
    firstName TEXT NOT NULL, 
    lastName TEXT NOT NULL, 
    aboutMe TEXT, 
    dateOfBirth TIMESTAMP NOT NULL,
    isPublic TEXT NOT NULL
);