CREATE TABLE IF NOT EXISTS comments (
    id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
    postId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    text TEXT DEFAULT "",
    creationDate INTEGER NOT NULL
);